package gotiktoklive

type RoomInfo struct {
	Data struct {
		AnchorABMap struct {
		} `json:"AnchorABMap"`
		AdminUserIds             []interface{} `json:"admin_user_ids"`
		AnchorScheduledTimeText  string        `json:"anchor_scheduled_time_text"`
		AnchorShareText          string        `json:"anchor_share_text"`
		AnchorTabType            int           `json:"anchor_tab_type"`
		AnsweringQuestionContent string        `json:"answering_question_content"`
		AppID                    int           `json:"app_id"`
		AutoCover                int           `json:"auto_cover"`
		BookEndTime              int           `json:"book_end_time"`
		BookTime                 int           `json:"book_time"`
		BusinessLive             int           `json:"business_live"`
		ChallengeInfo            string        `json:"challenge_info"`
		ClientVersion            int           `json:"client_version"`
		CommentNameMode          int           `json:"comment_name_mode"`
		CommerceInfo             struct {
			CommercePermission       int    `json:"commerce_permission"`
			OecLiveEnterRoomInitData string `json:"oec_live_enter_room_init_data"`
		} `json:"commerce_info"`
		CommonLabelList string `json:"common_label_list"`
		ContentTag      string `json:"content_tag"`
		Cover           struct {
			AvgColor   string   `json:"avg_color"`
			Height     int      `json:"height"`
			ImageType  int      `json:"image_type"`
			IsAnimated bool     `json:"is_animated"`
			OpenWebURL string   `json:"open_web_url"`
			URI        string   `json:"uri"`
			URLList    []string `json:"url_list"`
			Width      int      `json:"width"`
		} `json:"cover"`
		CreateTime           int           `json:"create_time"`
		DecoList             []interface{} `json:"deco_list"`
		DisablePreloadStream bool          `json:"disable_preload_stream"`
		FansclubMsgStyle     int           `json:"fansclub_msg_style"`
		FeedRoomLabel        struct {
			AvgColor   string   `json:"avg_color"`
			Height     int      `json:"height"`
			ImageType  int      `json:"image_type"`
			IsAnimated bool     `json:"is_animated"`
			OpenWebURL string   `json:"open_web_url"`
			URI        string   `json:"uri"`
			URLList    []string `json:"url_list"`
			Width      int      `json:"width"`
		} `json:"feed_room_label"`
		FeedRoomLabels      []interface{} `json:"feed_room_labels"`
		FilterMsgRules      []interface{} `json:"filter_msg_rules"`
		FinishReason        int           `json:"finish_reason"`
		FinishTime          int           `json:"finish_time"`
		FinishURL           string        `json:"finish_url"`
		FinishURLV2         string        `json:"finish_url_v2"`
		FollowMsgStyle      int           `json:"follow_msg_style"`
		ForumExtraData      string        `json:"forum_extra_data"`
		GameTag             []interface{} `json:"game_tag"`
		GiftMsgStyle        int           `json:"gift_msg_style"`
		GiftPollVoteEnabled bool          `json:"gift_poll_vote_enabled"`
		GroupSource         int           `json:"group_source"`
		HasCommerceGoods    bool          `json:"has_commerce_goods"`
		Hashtag             struct {
			ID    int `json:"id"`
			Image struct {
				AvgColor   string   `json:"avg_color"`
				Height     int      `json:"height"`
				ImageType  int      `json:"image_type"`
				IsAnimated bool     `json:"is_animated"`
				OpenWebURL string   `json:"open_web_url"`
				URI        string   `json:"uri"`
				URLList    []string `json:"url_list"`
				Width      int      `json:"width"`
			} `json:"image"`
			Namespace int    `json:"namespace"`
			Title     string `json:"title"`
		} `json:"hashtag"`
		HaveWishlist               bool   `json:"have_wishlist"`
		HotSentenceInfo            string `json:"hot_sentence_info"`
		ID                         int64  `json:"id"`
		IDStr                      string `json:"id_str"`
		InteractionQuestionVersion int    `json:"interaction_question_version"`
		Introduction               string `json:"introduction"`
		IsGatedRoom                bool   `json:"is_gated_room"`
		IsReplay                   bool   `json:"is_replay"`
		IsShowUserCardSwitch       bool   `json:"is_show_user_card_switch"`
		LastPingTime               int    `json:"last_ping_time"`
		Layout                     int    `json:"layout"`
		LikeCount                  int    `json:"like_count"`
		LinkMic                    struct {
			AudienceIDList []interface{} `json:"audience_id_list"`
			BattleScores   []interface{} `json:"battle_scores"`
			BattleSettings struct {
				BattleID    int    `json:"battle_id"`
				ChannelID   int    `json:"channel_id"`
				Duration    int    `json:"duration"`
				Finished    int    `json:"finished"`
				MatchType   int    `json:"match_type"`
				StartTime   int    `json:"start_time"`
				StartTimeMs int    `json:"start_time_ms"`
				Theme       string `json:"theme"`
			} `json:"battle_settings"`
			ChannelID      int           `json:"channel_id"`
			FollowedCount  int           `json:"followed_count"`
			LinkedUserList []interface{} `json:"linked_user_list"`
			MultiLiveEnum  int           `json:"multi_live_enum"`
			RivalAnchorID  int           `json:"rival_anchor_id"`
			ShowUserList   []interface{} `json:"show_user_list"`
		} `json:"link_mic"`
		LinkerMap struct {
		} `json:"linker_map"`
		LinkmicLayout      int           `json:"linkmic_layout"`
		LiveDistribution   []interface{} `json:"live_distribution"`
		LiveID             int           `json:"live_id"`
		LiveReason         string        `json:"live_reason"`
		LiveRoomMode       int           `json:"live_room_mode"`
		LiveTypeAudio      bool          `json:"live_type_audio"`
		LiveTypeLinkmic    bool          `json:"live_type_linkmic"`
		LiveTypeNormal     bool          `json:"live_type_normal"`
		LiveTypeSandbox    bool          `json:"live_type_sandbox"`
		LiveTypeScreenshot bool          `json:"live_type_screenshot"`
		LiveTypeSocialLive bool          `json:"live_type_social_live"`
		LiveTypeThirdParty bool          `json:"live_type_third_party"`
		LivingRoomAttrs    struct {
			AdminFlag   int    `json:"admin_flag"`
			Rank        int    `json:"rank"`
			RoomID      int64  `json:"room_id"`
			RoomIDStr   string `json:"room_id_str"`
			SilenceFlag int    `json:"silence_flag"`
		} `json:"living_room_attrs"`
		LotteryFinishTime int `json:"lottery_finish_time"`
		MosaicStatus      int `json:"mosaic_status"`
		OsType            int `json:"os_type"`
		Owner             struct {
			AllowFindByContacts                 bool `json:"allow_find_by_contacts"`
			AllowOthersDownloadVideo            bool `json:"allow_others_download_video"`
			AllowOthersDownloadWhenSharingVideo bool `json:"allow_others_download_when_sharing_video"`
			AllowShareShowProfile               bool `json:"allow_share_show_profile"`
			AllowShowInGossip                   bool `json:"allow_show_in_gossip"`
			AllowShowMyAction                   bool `json:"allow_show_my_action"`
			AllowStrangeComment                 bool `json:"allow_strange_comment"`
			AllowUnfollowerComment              bool `json:"allow_unfollower_comment"`
			AllowUseLinkmic                     bool `json:"allow_use_linkmic"`
			AvatarLarge                         struct {
				AvgColor   string   `json:"avg_color"`
				Height     int      `json:"height"`
				ImageType  int      `json:"image_type"`
				IsAnimated bool     `json:"is_animated"`
				OpenWebURL string   `json:"open_web_url"`
				URI        string   `json:"uri"`
				URLList    []string `json:"url_list"`
				Width      int      `json:"width"`
			} `json:"avatar_large"`
			AvatarMedium struct {
				AvgColor   string   `json:"avg_color"`
				Height     int      `json:"height"`
				ImageType  int      `json:"image_type"`
				IsAnimated bool     `json:"is_animated"`
				OpenWebURL string   `json:"open_web_url"`
				URI        string   `json:"uri"`
				URLList    []string `json:"url_list"`
				Width      int      `json:"width"`
			} `json:"avatar_medium"`
			AvatarThumb struct {
				AvgColor   string   `json:"avg_color"`
				Height     int      `json:"height"`
				ImageType  int      `json:"image_type"`
				IsAnimated bool     `json:"is_animated"`
				OpenWebURL string   `json:"open_web_url"`
				URI        string   `json:"uri"`
				URLList    []string `json:"url_list"`
				Width      int      `json:"width"`
			} `json:"avatar_thumb"`
			BadgeImageList           []interface{} `json:"badge_image_list"`
			BadgeList                []interface{} `json:"badge_list"`
			BgImgURL                 string        `json:"bg_img_url"`
			BioDescription           string        `json:"bio_description"`
			BlockStatus              int           `json:"block_status"`
			BorderList               []interface{} `json:"border_list"`
			CommentRestrict          int           `json:"comment_restrict"`
			CommerceWebcastConfigIds []interface{} `json:"commerce_webcast_config_ids"`
			Constellation            string        `json:"constellation"`
			CreateTime               int           `json:"create_time"`
			DisableIchat             int           `json:"disable_ichat"`
			DisplayID                string        `json:"display_id"`
			EnableIchatImg           int           `json:"enable_ichat_img"`
			Exp                      int           `json:"exp"`
			FanTicketCount           int           `json:"fan_ticket_count"`
			FoldStrangerChat         bool          `json:"fold_stranger_chat"`
			FollowInfo               struct {
				FollowStatus   int `json:"follow_status"`
				FollowerCount  int `json:"follower_count"`
				FollowingCount int `json:"following_count"`
				PushStatus     int `json:"push_status"`
			} `json:"follow_info"`
			FollowStatus        int           `json:"follow_status"`
			IchatRestrictType   int           `json:"ichat_restrict_type"`
			ID                  int           `json:"id"`
			IDStr               string        `json:"id_str"`
			IsFollower          bool          `json:"is_follower"`
			IsFollowing         bool          `json:"is_following"`
			LinkMicStats        int           `json:"link_mic_stats"`
			MediaBadgeImageList []interface{} `json:"media_badge_image_list"`
			ModifyTime          int           `json:"modify_time"`
			NeedProfileGuide    bool          `json:"need_profile_guide"`
			NewRealTimeIcons    []interface{} `json:"new_real_time_icons"`
			Nickname            string        `json:"nickname"`
			OwnRoom             struct {
				RoomIds    []int64  `json:"room_ids"`
				RoomIdsStr []string `json:"room_ids_str"`
			} `json:"own_room"`
			PayGrade struct {
				GradeBanner        string        `json:"grade_banner"`
				GradeDescribe      string        `json:"grade_describe"`
				GradeIconList      []interface{} `json:"grade_icon_list"`
				Level              int           `json:"level"`
				Name               string        `json:"name"`
				NextName           string        `json:"next_name"`
				NextPrivileges     string        `json:"next_privileges"`
				Score              int           `json:"score"`
				ScreenChatType     int           `json:"screen_chat_type"`
				UpgradeNeedConsume int           `json:"upgrade_need_consume"`
			} `json:"pay_grade"`
			PayScore           int           `json:"pay_score"`
			PayScores          int           `json:"pay_scores"`
			PushCommentStatus  bool          `json:"push_comment_status"`
			PushDigg           bool          `json:"push_digg"`
			PushFollow         bool          `json:"push_follow"`
			PushFriendAction   bool          `json:"push_friend_action"`
			PushIchat          bool          `json:"push_ichat"`
			PushStatus         bool          `json:"push_status"`
			PushVideoPost      bool          `json:"push_video_post"`
			PushVideoRecommend bool          `json:"push_video_recommend"`
			RealTimeIcons      []interface{} `json:"real_time_icons"`
			SecUID             string        `json:"sec_uid"`
			Secret             int           `json:"secret"`
			ShareQrcodeURI     string        `json:"share_qrcode_uri"`
			SpecialID          string        `json:"special_id"`
			Status             int           `json:"status"`
			TicketCount        int           `json:"ticket_count"`
			TopFans            []interface{} `json:"top_fans"`
			TopVipNo           int           `json:"top_vip_no"`
			UserAttr           struct {
				IsAdmin      bool `json:"is_admin"`
				IsMuted      bool `json:"is_muted"`
				IsSuperAdmin bool `json:"is_super_admin"`
				MuteDuration int  `json:"mute_duration"`
			} `json:"user_attr"`
			UserRole                    int    `json:"user_role"`
			Verified                    bool   `json:"verified"`
			VerifiedContent             string `json:"verified_content"`
			VerifiedReason              string `json:"verified_reason"`
			WithCarManagementPermission bool   `json:"with_car_management_permission"`
			WithCommercePermission      bool   `json:"with_commerce_permission"`
			WithFusionShopEntry         bool   `json:"with_fusion_shop_entry"`
		} `json:"owner"`
		OwnerDeviceID        int    `json:"owner_device_id"`
		OwnerDeviceIDStr     string `json:"owner_device_id_str"`
		OwnerUserID          int    `json:"owner_user_id"`
		OwnerUserIDStr       string `json:"owner_user_id_str"`
		PreEnterTime         int    `json:"pre_enter_time"`
		PreviewFlowTag       int    `json:"preview_flow_tag"`
		RanklistAudienceType int    `json:"ranklist_audience_type"`
		RelationTag          string `json:"relation_tag"`
		Replay               bool   `json:"replay"`
		RoomAuditStatus      int    `json:"room_audit_status"`
		RoomAuth             struct {
			Banner              int  `json:"Banner"`
			BroadcastMessage    int  `json:"BroadcastMessage"`
			Chat                bool `json:"Chat"`
			ChatL2              bool `json:"ChatL2"`
			ChatSubOnly         bool `json:"ChatSubOnly"`
			Danmaku             bool `json:"Danmaku"`
			Digg                bool `json:"Digg"`
			DonationSticker     int  `json:"DonationSticker"`
			Gift                bool `json:"Gift"`
			GiftAnchorMt        int  `json:"GiftAnchorMt"`
			GiftPoll            int  `json:"GiftPoll"`
			GoldenEnvelope      int  `json:"GoldenEnvelope"`
			InteractionQuestion bool `json:"InteractionQuestion"`
			Landscape           int  `json:"Landscape"`
			LandscapeChat       int  `json:"LandscapeChat"`
			LuckMoney           bool `json:"LuckMoney"`
			Poll                int  `json:"Poll"`
			Promote             bool `json:"Promote"`
			Props               bool `json:"Props"`
			PublicScreen        int  `json:"PublicScreen"`
			QuickChat           int  `json:"QuickChat"`
			Rank                int  `json:"Rank"`
			RoomContributor     bool `json:"RoomContributor"`
			Share               bool `json:"Share"`
			ShareEffect         int  `json:"ShareEffect"`
			UserCard            bool `json:"UserCard"`
			UserCount           int  `json:"UserCount"`
			Viewers             bool `json:"Viewers"`
			TransactionHistory  int  `json:"transaction_history"`
		} `json:"room_auth"`
		RoomCreateAbParam string        `json:"room_create_ab_param"`
		RoomLayout        int           `json:"room_layout"`
		RoomStickerList   []interface{} `json:"room_sticker_list"`
		RoomTabs          []interface{} `json:"room_tabs"`
		RoomTag           int           `json:"room_tag"`
		ScrollConfig      string        `json:"scroll_config"`
		SearchID          int           `json:"search_id"`
		ShareMsgStyle     int           `json:"share_msg_style"`
		ShareURL          string        `json:"share_url"`
		ShortTitle        string        `json:"short_title"`
		ShortTouchItems   []interface{} `json:"short_touch_items"`
		SocialInteraction struct {
			MultiLive struct {
				UserSettings struct {
					MultiLiveApplyPermission int `json:"multi_live_apply_permission"`
				} `json:"user_settings"`
			} `json:"multi_live"`
		} `json:"social_interaction"`
		StartTime int `json:"start_time"`
		Stats     struct {
			DiggCount            int    `json:"digg_count"`
			EnterCount           int    `json:"enter_count"`
			FanTicket            int    `json:"fan_ticket"`
			FollowCount          int    `json:"follow_count"`
			GiftUvCount          int    `json:"gift_uv_count"`
			ID                   int64  `json:"id"`
			IDStr                string `json:"id_str"`
			LikeCount            int    `json:"like_count"`
			ReplayFanTicket      int    `json:"replay_fan_ticket"`
			ReplayViewers        int    `json:"replay_viewers"`
			ShareCount           int    `json:"share_count"`
			TotalUser            int    `json:"total_user"`
			TotalUserDesp        string `json:"total_user_desp"`
			UserCountComposition struct {
				MyFollow    float64 `json:"my_follow"`
				Other       float64 `json:"other"`
				VideoDetail int     `json:"video_detail"`
			} `json:"user_count_composition"`
			Watermelon int `json:"watermelon"`
		} `json:"stats"`
		Status      int           `json:"status"`
		StickerList []interface{} `json:"sticker_list"`
		StreamID    int64         `json:"stream_id"`
		StreamIDStr string        `json:"stream_id_str"`
		StreamURL   struct {
			CandidateResolution []string      `json:"candidate_resolution"`
			CompletePushUrls    []interface{} `json:"complete_push_urls"`
			DefaultResolution   string        `json:"default_resolution"`
			Extra               struct {
				AnchorInteractProfile   int  `json:"anchor_interact_profile"`
				AudienceInteractProfile int  `json:"audience_interact_profile"`
				BframeEnable            bool `json:"bframe_enable"`
				BitrateAdaptStrategy    int  `json:"bitrate_adapt_strategy"`
				Bytevc1Enable           bool `json:"bytevc1_enable"`
				DefaultBitrate          int  `json:"default_bitrate"`
				Fps                     int  `json:"fps"`
				GopSec                  int  `json:"gop_sec"`
				HardwareEncode          bool `json:"hardware_encode"`
				Height                  int  `json:"height"`
				MaxBitrate              int  `json:"max_bitrate"`
				MinBitrate              int  `json:"min_bitrate"`
				Roi                     bool `json:"roi"`
				SwRoi                   bool `json:"sw_roi"`
				VideoProfile            int  `json:"video_profile"`
				Width                   int  `json:"width"`
			} `json:"extra"`
			FlvPullURL struct {
				FullHd1 string `json:"FULL_HD1"`
				Hd1     string `json:"HD1"`
				Sd1     string `json:"SD1"`
				Sd2     string `json:"SD2"`
			} `json:"flv_pull_url"`
			FlvPullURLParams struct {
				FullHd1 string `json:"FULL_HD1"`
				Hd1     string `json:"HD1"`
				Sd1     string `json:"SD1"`
				Sd2     string `json:"SD2"`
			} `json:"flv_pull_url_params"`
			HlsPullURL    string `json:"hls_pull_url"`
			HlsPullURLMap struct {
			} `json:"hls_pull_url_map"`
			HlsPullURLParams string `json:"hls_pull_url_params"`
			ID               int64  `json:"id"`
			IDStr            string `json:"id_str"`
			LiveCoreSdkData  struct {
				PullData struct {
					Options struct {
						DefaultQuality struct {
							Level      int    `json:"level"`
							Name       string `json:"name"`
							Resolution string `json:"resolution"`
							SdkKey     string `json:"sdk_key"`
							VCodec     string `json:"v_codec"`
						} `json:"default_quality"`
						Qualities []struct {
							Level      int    `json:"level"`
							Name       string `json:"name"`
							Resolution string `json:"resolution"`
							SdkKey     string `json:"sdk_key"`
							VCodec     string `json:"v_codec"`
						} `json:"qualities"`
					} `json:"options"`
					StreamData string `json:"stream_data"`
				} `json:"pull_data"`
			} `json:"live_core_sdk_data"`
			Provider       int           `json:"provider"`
			PushUrls       []interface{} `json:"push_urls"`
			ResolutionName struct {
				Auto    string `json:"AUTO"`
				FullHd1 string `json:"FULL_HD1"`
				Hd1     string `json:"HD1"`
				Origion string `json:"ORIGION"`
				Sd1     string `json:"SD1"`
				Sd2     string `json:"SD2"`
			} `json:"resolution_name"`
			RtmpPullURL       string `json:"rtmp_pull_url"`
			RtmpPullURLParams string `json:"rtmp_pull_url_params"`
			RtmpPushURL       string `json:"rtmp_push_url"`
			RtmpPushURLParams string `json:"rtmp_push_url_params"`
			StreamControlType int    `json:"stream_control_type"`
		} `json:"stream_url"`
		StreamURLFilteredInfo struct {
			IsGatedRoom bool `json:"is_gated_room"`
			IsPaidEvent bool `json:"is_paid_event"`
		} `json:"stream_url_filtered_info"`
		Title   string `json:"title"`
		TopFans []struct {
			FanTicket int `json:"fan_ticket"`
			User      struct {
				AllowFindByContacts                 bool `json:"allow_find_by_contacts"`
				AllowOthersDownloadVideo            bool `json:"allow_others_download_video"`
				AllowOthersDownloadWhenSharingVideo bool `json:"allow_others_download_when_sharing_video"`
				AllowShareShowProfile               bool `json:"allow_share_show_profile"`
				AllowShowInGossip                   bool `json:"allow_show_in_gossip"`
				AllowShowMyAction                   bool `json:"allow_show_my_action"`
				AllowStrangeComment                 bool `json:"allow_strange_comment"`
				AllowUnfollowerComment              bool `json:"allow_unfollower_comment"`
				AllowUseLinkmic                     bool `json:"allow_use_linkmic"`
				AvatarLarge                         struct {
					AvgColor   string   `json:"avg_color"`
					Height     int      `json:"height"`
					ImageType  int      `json:"image_type"`
					IsAnimated bool     `json:"is_animated"`
					OpenWebURL string   `json:"open_web_url"`
					URI        string   `json:"uri"`
					URLList    []string `json:"url_list"`
					Width      int      `json:"width"`
				} `json:"avatar_large"`
				AvatarMedium struct {
					AvgColor   string   `json:"avg_color"`
					Height     int      `json:"height"`
					ImageType  int      `json:"image_type"`
					IsAnimated bool     `json:"is_animated"`
					OpenWebURL string   `json:"open_web_url"`
					URI        string   `json:"uri"`
					URLList    []string `json:"url_list"`
					Width      int      `json:"width"`
				} `json:"avatar_medium"`
				AvatarThumb struct {
					AvgColor   string   `json:"avg_color"`
					Height     int      `json:"height"`
					ImageType  int      `json:"image_type"`
					IsAnimated bool     `json:"is_animated"`
					OpenWebURL string   `json:"open_web_url"`
					URI        string   `json:"uri"`
					URLList    []string `json:"url_list"`
					Width      int      `json:"width"`
				} `json:"avatar_thumb"`
				BadgeImageList           []interface{} `json:"badge_image_list"`
				BadgeList                []interface{} `json:"badge_list"`
				BgImgURL                 string        `json:"bg_img_url"`
				BioDescription           string        `json:"bio_description"`
				BlockStatus              int           `json:"block_status"`
				BorderList               []interface{} `json:"border_list"`
				CommentRestrict          int           `json:"comment_restrict"`
				CommerceWebcastConfigIds []interface{} `json:"commerce_webcast_config_ids"`
				Constellation            string        `json:"constellation"`
				CreateTime               int           `json:"create_time"`
				DisableIchat             int           `json:"disable_ichat"`
				DisplayID                string        `json:"display_id"`
				EnableIchatImg           int           `json:"enable_ichat_img"`
				Exp                      int           `json:"exp"`
				FanTicketCount           int           `json:"fan_ticket_count"`
				FoldStrangerChat         bool          `json:"fold_stranger_chat"`
				FollowInfo               struct {
					FollowStatus   int `json:"follow_status"`
					FollowerCount  int `json:"follower_count"`
					FollowingCount int `json:"following_count"`
					PushStatus     int `json:"push_status"`
				} `json:"follow_info"`
				FollowStatus        int           `json:"follow_status"`
				IchatRestrictType   int           `json:"ichat_restrict_type"`
				ID                  int64         `json:"id"`
				IDStr               string        `json:"id_str"`
				IsFollower          bool          `json:"is_follower"`
				IsFollowing         bool          `json:"is_following"`
				LinkMicStats        int           `json:"link_mic_stats"`
				MediaBadgeImageList []interface{} `json:"media_badge_image_list"`
				ModifyTime          int           `json:"modify_time"`
				NeedProfileGuide    bool          `json:"need_profile_guide"`
				NewRealTimeIcons    []interface{} `json:"new_real_time_icons"`
				Nickname            string        `json:"nickname"`
				PayGrade            struct {
					GradeBanner        string        `json:"grade_banner"`
					GradeDescribe      string        `json:"grade_describe"`
					GradeIconList      []interface{} `json:"grade_icon_list"`
					Level              int           `json:"level"`
					Name               string        `json:"name"`
					NextName           string        `json:"next_name"`
					NextPrivileges     string        `json:"next_privileges"`
					Score              int           `json:"score"`
					ScreenChatType     int           `json:"screen_chat_type"`
					UpgradeNeedConsume int           `json:"upgrade_need_consume"`
				} `json:"pay_grade"`
				PayScore           int           `json:"pay_score"`
				PayScores          int           `json:"pay_scores"`
				PushCommentStatus  bool          `json:"push_comment_status"`
				PushDigg           bool          `json:"push_digg"`
				PushFollow         bool          `json:"push_follow"`
				PushFriendAction   bool          `json:"push_friend_action"`
				PushIchat          bool          `json:"push_ichat"`
				PushStatus         bool          `json:"push_status"`
				PushVideoPost      bool          `json:"push_video_post"`
				PushVideoRecommend bool          `json:"push_video_recommend"`
				RealTimeIcons      []interface{} `json:"real_time_icons"`
				SecUID             string        `json:"sec_uid"`
				Secret             int           `json:"secret"`
				ShareQrcodeURI     string        `json:"share_qrcode_uri"`
				SpecialID          string        `json:"special_id"`
				Status             int           `json:"status"`
				TicketCount        int           `json:"ticket_count"`
				TopFans            []interface{} `json:"top_fans"`
				TopVipNo           int           `json:"top_vip_no"`
				UserAttr           struct {
					IsAdmin      bool `json:"is_admin"`
					IsMuted      bool `json:"is_muted"`
					IsSuperAdmin bool `json:"is_super_admin"`
					MuteDuration int  `json:"mute_duration"`
				} `json:"user_attr"`
				UserRole                    int    `json:"user_role"`
				Verified                    bool   `json:"verified"`
				VerifiedContent             string `json:"verified_content"`
				VerifiedReason              string `json:"verified_reason"`
				WithCarManagementPermission bool   `json:"with_car_management_permission"`
				WithCommercePermission      bool   `json:"with_commerce_permission"`
				WithFusionShopEntry         bool   `json:"with_fusion_shop_entry"`
			} `json:"user"`
		} `json:"top_fans"`
		UseFilter         bool   `json:"use_filter"`
		UserCount         int    `json:"user_count"`
		UserShareText     string `json:"user_share_text"`
		VideoFeedTag      string `json:"video_feed_tag"`
		WebcastCommentTcs int    `json:"webcast_comment_tcs"`
		WebcastSdkVersion int    `json:"webcast_sdk_version"`
		WithDrawSomething bool   `json:"with_draw_something"`
		WithKtv           bool   `json:"with_ktv"`
		WithLinkmic       bool   `json:"with_linkmic"`
	} `json:"data"`
	Extra struct {
		Now int64 `json:"now"`
	} `json:"extra"`
	StatusCode int `json:"status_code"`
}
