// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: proto/tiktok.proto

package gotiktoklive

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Data structure from im/fetch/ response
type WebcastResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*Message      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Cursor   string          `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	AckIds   string          `protobuf:"bytes,5,opt,name=ackIds,proto3" json:"ackIds,omitempty"`
	WsParam  *WebsocketParam `protobuf:"bytes,7,opt,name=wsParam,proto3" json:"wsParam,omitempty"`
	WsUrl    string          `protobuf:"bytes,10,opt,name=wsUrl,proto3" json:"wsUrl,omitempty"`
}

func (x *WebcastResponse) Reset() {
	*x = WebcastResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebcastResponse) ProtoMessage() {}

func (x *WebcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebcastResponse.ProtoReflect.Descriptor instead.
func (*WebcastResponse) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{0}
}

func (x *WebcastResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *WebcastResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *WebcastResponse) GetAckIds() string {
	if x != nil {
		return x.AckIds
	}
	return ""
}

func (x *WebcastResponse) GetWsParam() *WebsocketParam {
	if x != nil {
		return x.WsParam
	}
	return nil
}

func (x *WebcastResponse) GetWsUrl() string {
	if x != nil {
		return x.WsUrl
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Binary []byte `protobuf:"bytes,2,opt,name=binary,proto3" json:"binary,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetBinary() []byte {
	if x != nil {
		return x.Binary
	}
	return nil
}

type WebsocketParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *WebsocketParam) Reset() {
	*x = WebsocketParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebsocketParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketParam) ProtoMessage() {}

func (x *WebsocketParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketParam.ProtoReflect.Descriptor instead.
func (*WebsocketParam) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{2}
}

func (x *WebsocketParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WebsocketParam) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Message types depending on Message.tyoe
type WebcastControlMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action int32 `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *WebcastControlMessage) Reset() {
	*x = WebcastControlMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebcastControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebcastControlMessage) ProtoMessage() {}

func (x *WebcastControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebcastControlMessage.ProtoReflect.Descriptor instead.
func (*WebcastControlMessage) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{3}
}

func (x *WebcastControlMessage) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

// Statistics like viewer count
type WebcastRoomUserSeqMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ViewerCount int32 `protobuf:"varint,3,opt,name=viewerCount,proto3" json:"viewerCount,omitempty"`
}

func (x *WebcastRoomUserSeqMessage) Reset() {
	*x = WebcastRoomUserSeqMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebcastRoomUserSeqMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebcastRoomUserSeqMessage) ProtoMessage() {}

func (x *WebcastRoomUserSeqMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebcastRoomUserSeqMessage.ProtoReflect.Descriptor instead.
func (*WebcastRoomUserSeqMessage) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{4}
}

func (x *WebcastRoomUserSeqMessage) GetViewerCount() int32 {
	if x != nil {
		return x.ViewerCount
	}
	return 0
}

type WebcastChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User    *User  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Comment string `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *WebcastChatMessage) Reset() {
	*x = WebcastChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebcastChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebcastChatMessage) ProtoMessage() {}

func (x *WebcastChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebcastChatMessage.ProtoReflect.Descriptor instead.
func (*WebcastChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{5}
}

func (x *WebcastChatMessage) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *WebcastChatMessage) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type WebcastMemberMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User  *User                `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Event *WebcastMessageEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *WebcastMemberMessage) Reset() {
	*x = WebcastMemberMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebcastMemberMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebcastMemberMessage) ProtoMessage() {}

func (x *WebcastMemberMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebcastMemberMessage.ProtoReflect.Descriptor instead.
func (*WebcastMemberMessage) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{6}
}

func (x *WebcastMemberMessage) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *WebcastMemberMessage) GetEvent() *WebcastMessageEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type WebcastGiftMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User     *User  `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	GiftJson string `protobuf:"bytes,22,opt,name=giftJson,proto3" json:"giftJson,omitempty"`
}

func (x *WebcastGiftMessage) Reset() {
	*x = WebcastGiftMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebcastGiftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebcastGiftMessage) ProtoMessage() {}

func (x *WebcastGiftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebcastGiftMessage.ProtoReflect.Descriptor instead.
func (*WebcastGiftMessage) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{7}
}

func (x *WebcastGiftMessage) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *WebcastGiftMessage) GetGiftJson() string {
	if x != nil {
		return x.GiftJson
	}
	return ""
}

// Battle start
type WebcastLinkMicBattle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleUsers []*WebcastLinkMicBattleItems `protobuf:"bytes,10,rep,name=battleUsers,proto3" json:"battleUsers,omitempty"`
}

func (x *WebcastLinkMicBattle) Reset() {
	*x = WebcastLinkMicBattle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebcastLinkMicBattle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebcastLinkMicBattle) ProtoMessage() {}

func (x *WebcastLinkMicBattle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebcastLinkMicBattle.ProtoReflect.Descriptor instead.
func (*WebcastLinkMicBattle) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{8}
}

func (x *WebcastLinkMicBattle) GetBattleUsers() []*WebcastLinkMicBattleItems {
	if x != nil {
		return x.BattleUsers
	}
	return nil
}

type WebcastLinkMicBattleItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleGroup *WebcastLinkMicBattleGroup `protobuf:"bytes,2,opt,name=battleGroup,proto3" json:"battleGroup,omitempty"`
}

func (x *WebcastLinkMicBattleItems) Reset() {
	*x = WebcastLinkMicBattleItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebcastLinkMicBattleItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebcastLinkMicBattleItems) ProtoMessage() {}

func (x *WebcastLinkMicBattleItems) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebcastLinkMicBattleItems.ProtoReflect.Descriptor instead.
func (*WebcastLinkMicBattleItems) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{9}
}

func (x *WebcastLinkMicBattleItems) GetBattleGroup() *WebcastLinkMicBattleGroup {
	if x != nil {
		return x.BattleGroup
	}
	return nil
}

type WebcastLinkMicBattleGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *LinkUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *WebcastLinkMicBattleGroup) Reset() {
	*x = WebcastLinkMicBattleGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebcastLinkMicBattleGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebcastLinkMicBattleGroup) ProtoMessage() {}

func (x *WebcastLinkMicBattleGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebcastLinkMicBattleGroup.ProtoReflect.Descriptor instead.
func (*WebcastLinkMicBattleGroup) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{10}
}

func (x *WebcastLinkMicBattleGroup) GetUser() *LinkUser {
	if x != nil {
		return x.User
	}
	return nil
}

// Battle status
type WebcastLinkMicArmies struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleItems  []*WebcastLinkMicArmiesItems `protobuf:"bytes,3,rep,name=battleItems,proto3" json:"battleItems,omitempty"`
	BattleStatus int32                        `protobuf:"varint,7,opt,name=battleStatus,proto3" json:"battleStatus,omitempty"`
}

func (x *WebcastLinkMicArmies) Reset() {
	*x = WebcastLinkMicArmies{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebcastLinkMicArmies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebcastLinkMicArmies) ProtoMessage() {}

func (x *WebcastLinkMicArmies) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebcastLinkMicArmies.ProtoReflect.Descriptor instead.
func (*WebcastLinkMicArmies) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{11}
}

func (x *WebcastLinkMicArmies) GetBattleItems() []*WebcastLinkMicArmiesItems {
	if x != nil {
		return x.BattleItems
	}
	return nil
}

func (x *WebcastLinkMicArmies) GetBattleStatus() int32 {
	if x != nil {
		return x.BattleStatus
	}
	return 0
}

type WebcastLinkMicArmiesItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostUserId   uint64                       `protobuf:"varint,1,opt,name=hostUserId,proto3" json:"hostUserId,omitempty"`
	BattleGroups []*WebcastLinkMicArmiesGroup `protobuf:"bytes,2,rep,name=battleGroups,proto3" json:"battleGroups,omitempty"`
}

func (x *WebcastLinkMicArmiesItems) Reset() {
	*x = WebcastLinkMicArmiesItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebcastLinkMicArmiesItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebcastLinkMicArmiesItems) ProtoMessage() {}

func (x *WebcastLinkMicArmiesItems) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebcastLinkMicArmiesItems.ProtoReflect.Descriptor instead.
func (*WebcastLinkMicArmiesItems) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{12}
}

func (x *WebcastLinkMicArmiesItems) GetHostUserId() uint64 {
	if x != nil {
		return x.HostUserId
	}
	return 0
}

func (x *WebcastLinkMicArmiesItems) GetBattleGroups() []*WebcastLinkMicArmiesGroup {
	if x != nil {
		return x.BattleGroups
	}
	return nil
}

type WebcastLinkMicArmiesGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users  []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Points int32   `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"`
}

func (x *WebcastLinkMicArmiesGroup) Reset() {
	*x = WebcastLinkMicArmiesGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebcastLinkMicArmiesGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebcastLinkMicArmiesGroup) ProtoMessage() {}

func (x *WebcastLinkMicArmiesGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebcastLinkMicArmiesGroup.ProtoReflect.Descriptor instead.
func (*WebcastLinkMicArmiesGroup) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{13}
}

func (x *WebcastLinkMicArmiesGroup) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *WebcastLinkMicArmiesGroup) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

// Follow & share event
type WebcastSocialMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User  *User                `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Event *WebcastMessageEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *WebcastSocialMessage) Reset() {
	*x = WebcastSocialMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebcastSocialMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebcastSocialMessage) ProtoMessage() {}

func (x *WebcastSocialMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebcastSocialMessage.ProtoReflect.Descriptor instead.
func (*WebcastSocialMessage) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{14}
}

func (x *WebcastSocialMessage) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *WebcastSocialMessage) GetEvent() *WebcastMessageEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

// Like event (is only sent from time to time, not with every like)
type WebcastLikeMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User           *User                `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Event          *WebcastMessageEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	LikeCount      int32                `protobuf:"varint,2,opt,name=likeCount,proto3" json:"likeCount,omitempty"`
	TotalLikeCount int32                `protobuf:"varint,3,opt,name=totalLikeCount,proto3" json:"totalLikeCount,omitempty"`
}

func (x *WebcastLikeMessage) Reset() {
	*x = WebcastLikeMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebcastLikeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebcastLikeMessage) ProtoMessage() {}

func (x *WebcastLikeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebcastLikeMessage.ProtoReflect.Descriptor instead.
func (*WebcastLikeMessage) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{15}
}

func (x *WebcastLikeMessage) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *WebcastLikeMessage) GetEvent() *WebcastMessageEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *WebcastLikeMessage) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *WebcastLikeMessage) GetTotalLikeCount() int32 {
	if x != nil {
		return x.TotalLikeCount
	}
	return 0
}

// New question event
type WebcastQuestionNewMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuestionDetails *QuestionDetails `protobuf:"bytes,2,opt,name=questionDetails,proto3" json:"questionDetails,omitempty"`
}

func (x *WebcastQuestionNewMessage) Reset() {
	*x = WebcastQuestionNewMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebcastQuestionNewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebcastQuestionNewMessage) ProtoMessage() {}

func (x *WebcastQuestionNewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebcastQuestionNewMessage.ProtoReflect.Descriptor instead.
func (*WebcastQuestionNewMessage) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{16}
}

func (x *WebcastQuestionNewMessage) GetQuestionDetails() *QuestionDetails {
	if x != nil {
		return x.QuestionDetails
	}
	return nil
}

type QuestionDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuestionText string `protobuf:"bytes,2,opt,name=questionText,proto3" json:"questionText,omitempty"`
	User         *User  `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *QuestionDetails) Reset() {
	*x = QuestionDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuestionDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionDetails) ProtoMessage() {}

func (x *QuestionDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionDetails.ProtoReflect.Descriptor instead.
func (*QuestionDetails) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{17}
}

func (x *QuestionDetails) GetQuestionText() string {
	if x != nil {
		return x.QuestionText
	}
	return ""
}

func (x *QuestionDetails) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type WebcastMessageEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventDetails *WebcastMessageEventDetails `protobuf:"bytes,8,opt,name=eventDetails,proto3" json:"eventDetails,omitempty"`
}

func (x *WebcastMessageEvent) Reset() {
	*x = WebcastMessageEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebcastMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebcastMessageEvent) ProtoMessage() {}

func (x *WebcastMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebcastMessageEvent.ProtoReflect.Descriptor instead.
func (*WebcastMessageEvent) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{18}
}

func (x *WebcastMessageEvent) GetEventDetails() *WebcastMessageEventDetails {
	if x != nil {
		return x.EventDetails
	}
	return nil
}

// Contains UI information
type WebcastMessageEventDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DisplayType string `protobuf:"bytes,1,opt,name=displayType,proto3" json:"displayType,omitempty"`
	Label       string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *WebcastMessageEventDetails) Reset() {
	*x = WebcastMessageEventDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebcastMessageEventDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebcastMessageEventDetails) ProtoMessage() {}

func (x *WebcastMessageEventDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebcastMessageEventDetails.ProtoReflect.Descriptor instead.
func (*WebcastMessageEventDetails) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{19}
}

func (x *WebcastMessageEventDetails) GetDisplayType() string {
	if x != nil {
		return x.DisplayType
	}
	return ""
}

func (x *WebcastMessageEventDetails) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId          uint64                `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Nickname        string                `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	ProfilePicture  *ProfilePicture       `protobuf:"bytes,9,opt,name=profilePicture,proto3" json:"profilePicture,omitempty"`
	ExtraAttributes *UserExtraAttributes  `protobuf:"bytes,22,opt,name=extraAttributes,proto3" json:"extraAttributes,omitempty"`
	Badge           *UserBadgesAttributes `protobuf:"bytes,64,opt,name=badge,proto3" json:"badge,omitempty"`
	UniqueId        string                `protobuf:"bytes,38,opt,name=uniqueId,proto3" json:"uniqueId,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{20}
}

func (x *User) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetProfilePicture() *ProfilePicture {
	if x != nil {
		return x.ProfilePicture
	}
	return nil
}

func (x *User) GetExtraAttributes() *UserExtraAttributes {
	if x != nil {
		return x.ExtraAttributes
	}
	return nil
}

func (x *User) GetBadge() *UserBadgesAttributes {
	if x != nil {
		return x.Badge
	}
	return nil
}

func (x *User) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

type LinkUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         uint64          `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Nickname       string          `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	ProfilePicture *ProfilePicture `protobuf:"bytes,3,opt,name=profilePicture,proto3" json:"profilePicture,omitempty"`
	UniqueId       string          `protobuf:"bytes,4,opt,name=uniqueId,proto3" json:"uniqueId,omitempty"`
}

func (x *LinkUser) Reset() {
	*x = LinkUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkUser) ProtoMessage() {}

func (x *LinkUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkUser.ProtoReflect.Descriptor instead.
func (*LinkUser) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{21}
}

func (x *LinkUser) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LinkUser) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *LinkUser) GetProfilePicture() *ProfilePicture {
	if x != nil {
		return x.ProfilePicture
	}
	return nil
}

func (x *LinkUser) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

type ProfilePicture struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []string `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *ProfilePicture) Reset() {
	*x = ProfilePicture{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfilePicture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilePicture) ProtoMessage() {}

func (x *ProfilePicture) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilePicture.ProtoReflect.Descriptor instead.
func (*ProfilePicture) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{22}
}

func (x *ProfilePicture) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type UserExtraAttributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FollowRole int32 `protobuf:"varint,3,opt,name=followRole,proto3" json:"followRole,omitempty"`
}

func (x *UserExtraAttributes) Reset() {
	*x = UserExtraAttributes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserExtraAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserExtraAttributes) ProtoMessage() {}

func (x *UserExtraAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserExtraAttributes.ProtoReflect.Descriptor instead.
func (*UserExtraAttributes) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{23}
}

func (x *UserExtraAttributes) GetFollowRole() int32 {
	if x != nil {
		return x.FollowRole
	}
	return 0
}

type UserBadgesAttributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Badges []*UserBadge `protobuf:"bytes,21,rep,name=badges,proto3" json:"badges,omitempty"`
}

func (x *UserBadgesAttributes) Reset() {
	*x = UserBadgesAttributes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBadgesAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBadgesAttributes) ProtoMessage() {}

func (x *UserBadgesAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBadgesAttributes.ProtoReflect.Descriptor instead.
func (*UserBadgesAttributes) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{24}
}

func (x *UserBadgesAttributes) GetBadges() []*UserBadge {
	if x != nil {
		return x.Badges
	}
	return nil
}

type UserBadge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UserBadge) Reset() {
	*x = UserBadge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBadge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBadge) ProtoMessage() {}

func (x *UserBadge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBadge.ProtoReflect.Descriptor instead.
func (*UserBadge) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{25}
}

func (x *UserBadge) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UserBadge) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Websocket incoming message structure
type WebcastWebsocketMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Type   string `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Binary []byte `protobuf:"bytes,8,opt,name=binary,proto3" json:"binary,omitempty"`
}

func (x *WebcastWebsocketMessage) Reset() {
	*x = WebcastWebsocketMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebcastWebsocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebcastWebsocketMessage) ProtoMessage() {}

func (x *WebcastWebsocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebcastWebsocketMessage.ProtoReflect.Descriptor instead.
func (*WebcastWebsocketMessage) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{26}
}

func (x *WebcastWebsocketMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WebcastWebsocketMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WebcastWebsocketMessage) GetBinary() []byte {
	if x != nil {
		return x.Binary
	}
	return nil
}

// Websocket acknowledgment message
type WebcastWebsocketAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Type string `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *WebcastWebsocketAck) Reset() {
	*x = WebcastWebsocketAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tiktok_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebcastWebsocketAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebcastWebsocketAck) ProtoMessage() {}

func (x *WebcastWebsocketAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tiktok_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebcastWebsocketAck.ProtoReflect.Descriptor instead.
func (*WebcastWebsocketAck) Descriptor() ([]byte, []int) {
	return file_proto_tiktok_proto_rawDescGZIP(), []int{27}
}

func (x *WebcastWebsocketAck) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WebcastWebsocketAck) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_proto_tiktok_proto protoreflect.FileDescriptor

var file_proto_tiktok_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x69, 0x6b, 0x74, 0x6f, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x22, 0xb6, 0x01, 0x0a,
	0x0f, 0x57, 0x65, 0x62, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2b, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x73, 0x12, 0x30, 0x0a,
	0x07, 0x77, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x2e, 0x57, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65,
	0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x07, 0x77, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12,
	0x14, 0x0a, 0x05, 0x77, 0x73, 0x55, 0x72, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x77, 0x73, 0x55, 0x72, 0x6c, 0x22, 0x35, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x22, 0x3a, 0x0a, 0x0e,
	0x57, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2f, 0x0a, 0x15, 0x57, 0x65, 0x62, 0x63,
	0x61, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3d, 0x0a, 0x19, 0x57, 0x65, 0x62,
	0x63, 0x61, 0x73, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x76, 0x69, 0x65,
	0x77, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x50, 0x0a, 0x12, 0x57, 0x65, 0x62, 0x63,
	0x61, 0x73, 0x74, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54,
	0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x6b, 0x0a, 0x14, 0x57, 0x65,
	0x62, 0x63, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x2e, 0x57, 0x65, 0x62,
	0x63, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x52, 0x0a, 0x12, 0x57, 0x65, 0x62, 0x63, 0x61,
	0x73, 0x74, 0x47, 0x69, 0x66, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x69,
	0x6b, 0x54, 0x6f, 0x6b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x67, 0x69, 0x66, 0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x18, 0x16, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x67, 0x69, 0x66, 0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x5b, 0x0a, 0x14, 0x57,
	0x65, 0x62, 0x63, 0x61, 0x73, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x4d, 0x69, 0x63, 0x42, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x12, 0x43, 0x0a, 0x0b, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x54, 0x69, 0x6b, 0x54, 0x6f,
	0x6b, 0x2e, 0x57, 0x65, 0x62, 0x63, 0x61, 0x73, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x4d, 0x69, 0x63,
	0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x0b, 0x62, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x22, 0x60, 0x0a, 0x19, 0x57, 0x65, 0x62, 0x63,
	0x61, 0x73, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x4d, 0x69, 0x63, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x43, 0x0a, 0x0b, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x54, 0x69, 0x6b,
	0x54, 0x6f, 0x6b, 0x2e, 0x57, 0x65, 0x62, 0x63, 0x61, 0x73, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x4d,
	0x69, 0x63, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x0b, 0x62,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x41, 0x0a, 0x19, 0x57, 0x65,
	0x62, 0x63, 0x61, 0x73, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x4d, 0x69, 0x63, 0x42, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x24, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x2e, 0x4c,
	0x69, 0x6e, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x7f, 0x0a,
	0x14, 0x57, 0x65, 0x62, 0x63, 0x61, 0x73, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x4d, 0x69, 0x63, 0x41,
	0x72, 0x6d, 0x69, 0x65, 0x73, 0x12, 0x43, 0x0a, 0x0b, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x54, 0x69, 0x6b,
	0x54, 0x6f, 0x6b, 0x2e, 0x57, 0x65, 0x62, 0x63, 0x61, 0x73, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x4d,
	0x69, 0x63, 0x41, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x0b, 0x62,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x82,
	0x01, 0x0a, 0x19, 0x57, 0x65, 0x62, 0x63, 0x61, 0x73, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x4d, 0x69,
	0x63, 0x41, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1e, 0x0a, 0x0a,
	0x68, 0x6f, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0a, 0x68, 0x6f, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x45, 0x0a, 0x0c,
	0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x2e, 0x57, 0x65, 0x62, 0x63,
	0x61, 0x73, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x4d, 0x69, 0x63, 0x41, 0x72, 0x6d, 0x69, 0x65, 0x73,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x0c, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x73, 0x22, 0x57, 0x0a, 0x19, 0x57, 0x65, 0x62, 0x63, 0x61, 0x73, 0x74, 0x4c, 0x69,
	0x6e, 0x6b, 0x4d, 0x69, 0x63, 0x41, 0x72, 0x6d, 0x69, 0x65, 0x73, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x22, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75,
	0x73, 0x65, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x6b, 0x0a, 0x14,
	0x57, 0x65, 0x62, 0x63, 0x61, 0x73, 0x74, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x2e, 0x57,
	0x65, 0x62, 0x63, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0xaf, 0x01, 0x0a, 0x12, 0x57, 0x65,
	0x62, 0x63, 0x61, 0x73, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x20, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x31, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x2e, 0x57, 0x65, 0x62, 0x63, 0x61,
	0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6c, 0x69, 0x6b, 0x65, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4c, 0x69, 0x6b, 0x65,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5e, 0x0a, 0x19, 0x57,
	0x65, 0x62, 0x63, 0x61, 0x73, 0x74, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x65,
	0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x41, 0x0a, 0x0f, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x0f, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x57, 0x0a, 0x0f, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x22,
	0x0a, 0x0c, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x65, 0x78, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x65,
	0x78, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x22, 0x5d, 0x0a, 0x13, 0x57, 0x65, 0x62, 0x63, 0x61, 0x73, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x46, 0x0a, 0x0c, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x2e, 0x57, 0x65, 0x62, 0x63, 0x61,
	0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x0c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x22, 0x54, 0x0a, 0x1a, 0x57, 0x65, 0x62, 0x63, 0x61, 0x73, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x91, 0x02, 0x0a, 0x04, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69,
	0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69,
	0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3e, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50,
	0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50,
	0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x45, 0x0a, 0x0f, 0x65, 0x78, 0x74, 0x72, 0x61, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x16, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x45, 0x78, 0x74,
	0x72, 0x61, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x52, 0x0f, 0x65, 0x78,
	0x74, 0x72, 0x61, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x32, 0x0a,
	0x05, 0x62, 0x61, 0x64, 0x67, 0x65, 0x18, 0x40, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x54,
	0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x64, 0x67, 0x65, 0x73,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x52, 0x05, 0x62, 0x61, 0x64, 0x67,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x18, 0x26, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x22, 0x9a, 0x01,
	0x0a, 0x08, 0x4c, 0x69, 0x6e, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3e,
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x2e,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x0e,
	0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x22, 0x24, 0x0a, 0x0e, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73,
	0x22, 0x35, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x45, 0x78, 0x74, 0x72, 0x61, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x66, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0x41, 0x0a, 0x14, 0x55, 0x73, 0x65, 0x72, 0x42,
	0x61, 0x64, 0x67, 0x65, 0x73, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12,
	0x29, 0x0a, 0x06, 0x62, 0x61, 0x64, 0x67, 0x65, 0x73, 0x18, 0x15, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x54, 0x69, 0x6b, 0x54, 0x6f, 0x6b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x64,
	0x67, 0x65, 0x52, 0x06, 0x62, 0x61, 0x64, 0x67, 0x65, 0x73, 0x22, 0x33, 0x0a, 0x09, 0x55, 0x73,
	0x65, 0x72, 0x42, 0x61, 0x64, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x55, 0x0a, 0x17, 0x57, 0x65, 0x62, 0x63, 0x61, 0x73, 0x74, 0x57, 0x65, 0x62, 0x73, 0x6f, 0x63,
	0x6b, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x22, 0x39, 0x0a, 0x13, 0x57, 0x65, 0x62, 0x63, 0x61, 0x73,
	0x74, 0x57, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x67, 0x6f, 0x74,
	0x69, 0x6b, 0x74, 0x6f, 0x6b, 0x6c, 0x69, 0x76, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_tiktok_proto_rawDescOnce sync.Once
	file_proto_tiktok_proto_rawDescData = file_proto_tiktok_proto_rawDesc
)

func file_proto_tiktok_proto_rawDescGZIP() []byte {
	file_proto_tiktok_proto_rawDescOnce.Do(func() {
		file_proto_tiktok_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_tiktok_proto_rawDescData)
	})
	return file_proto_tiktok_proto_rawDescData
}

var file_proto_tiktok_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_tiktok_proto_goTypes = []interface{}{
	(*WebcastResponse)(nil),            // 0: TikTok.WebcastResponse
	(*Message)(nil),                    // 1: TikTok.Message
	(*WebsocketParam)(nil),             // 2: TikTok.WebsocketParam
	(*WebcastControlMessage)(nil),      // 3: TikTok.WebcastControlMessage
	(*WebcastRoomUserSeqMessage)(nil),  // 4: TikTok.WebcastRoomUserSeqMessage
	(*WebcastChatMessage)(nil),         // 5: TikTok.WebcastChatMessage
	(*WebcastMemberMessage)(nil),       // 6: TikTok.WebcastMemberMessage
	(*WebcastGiftMessage)(nil),         // 7: TikTok.WebcastGiftMessage
	(*WebcastLinkMicBattle)(nil),       // 8: TikTok.WebcastLinkMicBattle
	(*WebcastLinkMicBattleItems)(nil),  // 9: TikTok.WebcastLinkMicBattleItems
	(*WebcastLinkMicBattleGroup)(nil),  // 10: TikTok.WebcastLinkMicBattleGroup
	(*WebcastLinkMicArmies)(nil),       // 11: TikTok.WebcastLinkMicArmies
	(*WebcastLinkMicArmiesItems)(nil),  // 12: TikTok.WebcastLinkMicArmiesItems
	(*WebcastLinkMicArmiesGroup)(nil),  // 13: TikTok.WebcastLinkMicArmiesGroup
	(*WebcastSocialMessage)(nil),       // 14: TikTok.WebcastSocialMessage
	(*WebcastLikeMessage)(nil),         // 15: TikTok.WebcastLikeMessage
	(*WebcastQuestionNewMessage)(nil),  // 16: TikTok.WebcastQuestionNewMessage
	(*QuestionDetails)(nil),            // 17: TikTok.QuestionDetails
	(*WebcastMessageEvent)(nil),        // 18: TikTok.WebcastMessageEvent
	(*WebcastMessageEventDetails)(nil), // 19: TikTok.WebcastMessageEventDetails
	(*User)(nil),                       // 20: TikTok.User
	(*LinkUser)(nil),                   // 21: TikTok.LinkUser
	(*ProfilePicture)(nil),             // 22: TikTok.ProfilePicture
	(*UserExtraAttributes)(nil),        // 23: TikTok.UserExtraAttributes
	(*UserBadgesAttributes)(nil),       // 24: TikTok.UserBadgesAttributes
	(*UserBadge)(nil),                  // 25: TikTok.UserBadge
	(*WebcastWebsocketMessage)(nil),    // 26: TikTok.WebcastWebsocketMessage
	(*WebcastWebsocketAck)(nil),        // 27: TikTok.WebcastWebsocketAck
}
var file_proto_tiktok_proto_depIdxs = []int32{
	1,  // 0: TikTok.WebcastResponse.messages:type_name -> TikTok.Message
	2,  // 1: TikTok.WebcastResponse.wsParam:type_name -> TikTok.WebsocketParam
	20, // 2: TikTok.WebcastChatMessage.user:type_name -> TikTok.User
	20, // 3: TikTok.WebcastMemberMessage.user:type_name -> TikTok.User
	18, // 4: TikTok.WebcastMemberMessage.event:type_name -> TikTok.WebcastMessageEvent
	20, // 5: TikTok.WebcastGiftMessage.user:type_name -> TikTok.User
	9,  // 6: TikTok.WebcastLinkMicBattle.battleUsers:type_name -> TikTok.WebcastLinkMicBattleItems
	10, // 7: TikTok.WebcastLinkMicBattleItems.battleGroup:type_name -> TikTok.WebcastLinkMicBattleGroup
	21, // 8: TikTok.WebcastLinkMicBattleGroup.user:type_name -> TikTok.LinkUser
	12, // 9: TikTok.WebcastLinkMicArmies.battleItems:type_name -> TikTok.WebcastLinkMicArmiesItems
	13, // 10: TikTok.WebcastLinkMicArmiesItems.battleGroups:type_name -> TikTok.WebcastLinkMicArmiesGroup
	20, // 11: TikTok.WebcastLinkMicArmiesGroup.users:type_name -> TikTok.User
	20, // 12: TikTok.WebcastSocialMessage.user:type_name -> TikTok.User
	18, // 13: TikTok.WebcastSocialMessage.event:type_name -> TikTok.WebcastMessageEvent
	20, // 14: TikTok.WebcastLikeMessage.user:type_name -> TikTok.User
	18, // 15: TikTok.WebcastLikeMessage.event:type_name -> TikTok.WebcastMessageEvent
	17, // 16: TikTok.WebcastQuestionNewMessage.questionDetails:type_name -> TikTok.QuestionDetails
	20, // 17: TikTok.QuestionDetails.user:type_name -> TikTok.User
	19, // 18: TikTok.WebcastMessageEvent.eventDetails:type_name -> TikTok.WebcastMessageEventDetails
	22, // 19: TikTok.User.profilePicture:type_name -> TikTok.ProfilePicture
	23, // 20: TikTok.User.extraAttributes:type_name -> TikTok.UserExtraAttributes
	24, // 21: TikTok.User.badge:type_name -> TikTok.UserBadgesAttributes
	22, // 22: TikTok.LinkUser.profilePicture:type_name -> TikTok.ProfilePicture
	25, // 23: TikTok.UserBadgesAttributes.badges:type_name -> TikTok.UserBadge
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_proto_tiktok_proto_init() }
func file_proto_tiktok_proto_init() {
	if File_proto_tiktok_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_tiktok_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebcastResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebsocketParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebcastControlMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebcastRoomUserSeqMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebcastChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebcastMemberMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebcastGiftMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebcastLinkMicBattle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebcastLinkMicBattleItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebcastLinkMicBattleGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebcastLinkMicArmies); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebcastLinkMicArmiesItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebcastLinkMicArmiesGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebcastSocialMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebcastLikeMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebcastQuestionNewMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuestionDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebcastMessageEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebcastMessageEventDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfilePicture); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserExtraAttributes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBadgesAttributes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBadge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebcastWebsocketMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_tiktok_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebcastWebsocketAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_tiktok_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_tiktok_proto_goTypes,
		DependencyIndexes: file_proto_tiktok_proto_depIdxs,
		MessageInfos:      file_proto_tiktok_proto_msgTypes,
	}.Build()
	File_proto_tiktok_proto = out.File
	file_proto_tiktok_proto_rawDesc = nil
	file_proto_tiktok_proto_goTypes = nil
	file_proto_tiktok_proto_depIdxs = nil
}
